/*
  Single source of truth for diagnostic codes.
  `Diagnostic.code` is narrowed to `DiagnosticCode`, so a typo anywhere in the
  parser, validators or generators is a compile error. Codes are stable
  identifiers: UI text can change, codes are never reused with a new meaning.
*/
export const DIAGNOSTIC_CODES = {
  // Phase 1: parse
  PARSE_UNRECOGNIZED_LINE: 'PARSE_UNRECOGNIZED_LINE',
  PARSE_UNKNOWN_ATTRIBUTE: 'PARSE_UNKNOWN_ATTRIBUTE',
  PARSE_UNTERMINATED_BLOCK: 'PARSE_UNTERMINATED_BLOCK',
  PARSE_INVALID_ENUM_DECLARATION: 'PARSE_INVALID_ENUM_DECLARATION',
  PARSE_INVALID_ENUM_VALUE: 'PARSE_INVALID_ENUM_VALUE',

  // Phase 2: schema validation
  SCHEMA_DUPLICATE_TABLE: 'SCHEMA_DUPLICATE_TABLE',
  SCHEMA_DUPLICATE_COLUMN: 'SCHEMA_DUPLICATE_COLUMN',
  SCHEMA_UNKNOWN_REFERENCE_TABLE: 'SCHEMA_UNKNOWN_REFERENCE_TABLE',
  SCHEMA_UNKNOWN_REFERENCE_COLUMN: 'SCHEMA_UNKNOWN_REFERENCE_COLUMN',
  SCHEMA_REFERENCE_TYPE_MISMATCH: 'SCHEMA_REFERENCE_TYPE_MISMATCH',
  SCHEMA_UNKNOWN_INDEX_COLUMN: 'SCHEMA_UNKNOWN_INDEX_COLUMN',
  SCHEMA_DUPLICATE_ENUM: 'SCHEMA_DUPLICATE_ENUM',
  SCHEMA_DUPLICATE_ENUM_VALUE: 'SCHEMA_DUPLICATE_ENUM_VALUE',
  SCHEMA_AMBIGUOUS_ENUM_TYPE: 'SCHEMA_AMBIGUOUS_ENUM_TYPE',
  SCHEMA_ENUM_TYPE_CASE_MISMATCH: 'SCHEMA_ENUM_TYPE_CASE_MISMATCH',
  SCHEMA_INVALID_ENUM_DEFAULT: 'SCHEMA_INVALID_ENUM_DEFAULT',

  // Parse-phase auto-completion (info)
  SCHEMA_FK_COLUMN_CREATED: 'SCHEMA_FK_COLUMN_CREATED',
  SCHEMA_JUNCTION_TABLE_CREATED: 'SCHEMA_JUNCTION_TABLE_CREATED',

  // Phase 3: output validation
  OUTPUT_UNKNOWN_TYPE_FALLBACK: 'OUTPUT_UNKNOWN_TYPE_FALLBACK',
  OUTPUT_NAME_COLLISION: 'OUTPUT_NAME_COLLISION',
  OUTPUT_PROPERTY_COLLISION: 'OUTPUT_PROPERTY_COLLISION',
  OUTPUT_INVALID_IDENTIFIER: 'OUTPUT_INVALID_IDENTIFIER',
  PRISMA_RESERVED_NAME: 'PRISMA_RESERVED_NAME',
  TYPEORM_IMPORT_NAME_COLLISION: 'TYPEORM_IMPORT_NAME_COLLISION',
} as const;

export type DiagnosticCode =
  (typeof DIAGNOSTIC_CODES)[keyof typeof DIAGNOSTIC_CODES];
